//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertising
    {
        public int AdvertisingID { get; set; }
        public string Adv_Name { get; set; }
        public System.DateTime Adv_Start { get; set; }
        public System.DateTime Adv_End { get; set; }
    }
}
