//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelDelivery
    {
        public int DeliveryID { get; set; }
        public int ID_Cistern { get; set; }
        public System.DateTime Data_delivery { get; set; }
    
        public virtual Cistern Cistern { get; set; }
    }
}
