//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lgn
    {
        public int LoginID { get; set; }
        public int ID_Cashier { get; set; }
        public string Login { get; set; }
        public string Last_login { get; set; }
        public string Password { get; set; }
        public string Last_Password { get; set; }
    
        public virtual Cashier Cashier { get; set; }
    }
}
