//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdPromotion
    {
        public int PromotionID { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public System.DateTime Prom_start { get; set; }
        public System.DateTime Prom_end { get; set; }
        public string Prom_type { get; set; }
        public int Prom_discount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
