//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int ShiftID { get; set; }
        public int ID_Cashier { get; set; }
        public int ID_Station { get; set; }
        public System.DateTime Shift_start { get; set; }
        public System.DateTime Shift_end { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Sales_volume { get; set; }
        public Nullable<decimal> Cash_amount_start { get; set; }
        public Nullable<decimal> Cash_amount_end { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
