//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_station
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cistern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cistern()
        {
            this.FuelDeliveries = new HashSet<FuelDelivery>();
        }
    
        public int ID_Cistern { get; set; }
        public int ID_Product { get; set; }
        public decimal MaxVolume { get; set; }
        public decimal MinVolume { get; set; }
        public decimal ActualVolume { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelDelivery> FuelDeliveries { get; set; }
    }
}
