//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_station
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public int ID_LoyaltyCard { get; set; }
        public int ID_Person { get; set; }
    
        public virtual LoyaltyCard LoyaltyCard { get; set; }
        public virtual Person Person { get; set; }
    }
}
