//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_station
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelDelivery
    {
        public int ID_Delivery { get; set; }
        public int ID_Cistern { get; set; }
        public System.DateTime DataDelivery { get; set; }
    
        public virtual Cistern Cistern { get; set; }
    }
}
