//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_station
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Cisterns = new HashSet<Cistern>();
            this.ProductReceipts = new HashSet<ProductReceipt>();
        }
    
        public int ProductID { get; set; }
        public string Pro_Name { get; set; }
        public string Pro_Description { get; set; }
        public Nullable<int> ID_Discount { get; set; }
        public int ID_Developer { get; set; }
        public int ID_Distributor { get; set; }
        public int ID_Category { get; set; }
        public int ID_Type_Product { get; set; }
        public decimal Pro_Price { get; set; }
        public Nullable<System.DateTime> Pro_LastUpdate { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cistern> Cisterns { get; set; }
        public virtual Developer Developer { get; set; }
        public virtual Distributor Distributor { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual Type_Product Type_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReceipt> ProductReceipts { get; set; }
    }
}
