//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_station
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Cisterns = new HashSet<Cistern>();
            this.ProdPromotions = new HashSet<ProdPromotion>();
            this.ProductReceipts = new HashSet<ProductReceipt>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Short_name { get; set; }
        public string Description { get; set; }
        public string Description1 { get; set; }
        public int ID_Developer { get; set; }
        public int ID_Distributor { get; set; }
        public int ID_Category { get; set; }
        public int ID_Type_Product { get; set; }
        public decimal List_price { get; set; }
        public decimal Stock_price { get; set; }
        public decimal StandartPrice { get; set; }
        public Nullable<System.DateTime> SellStartDate { get; set; }
        public Nullable<System.DateTime> SellEndDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Restriction_age { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cistern> Cisterns { get; set; }
        public virtual Developer Developer { get; set; }
        public virtual Distributor Distributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdPromotion> ProdPromotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReceipt> ProductReceipts { get; set; }
        public virtual Type_Product Type_Product { get; set; }
    }
}
