//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_station
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.ProductReceipts = new HashSet<ProductReceipt>();
        }
    
        public int ReceiptID { get; set; }
        public System.DateTime Deal_time { get; set; }
        public decimal Sel_price { get; set; }
        public decimal Discount_price { get; set; }
        public string NIP { get; set; }
        public string VRN { get; set; }
        public int ID_Shift { get; set; }
        public double Qt_product { get; set; }
        public Nullable<int> ID_Customer { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReceipt> ProductReceipts { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
